// Define possible resources for each action
export const actions = {
  fish: [
    { name: 'missed action', tier: 'Missed', chance: 0.15, min: 1, max: 1, value: 0},
    { name: 'salmon', tier: 'Common', chance: 0.40, min: 1, max: 3, value: 10 },
    { name: 'tuna', tier: 'Uncommon', chance: 0.25, min: 1, max: 2, value: 15 },
    { name: 'swordfish', tier: 'Rare', chance: 0.10, min: 1, max: 1, value: 25 },
    { name: 'shark', tier: 'Epic', chance: 0.05, min: 1, max: 1, value: 50 },
    { name: 'giant squid', tier: 'Legendary', chance: 0.04, min: 1, max: 1, value: 100 },
    { name: 'kraken', tier: 'Mythic', chance: 0.01, min: 1, max: 1, value: 200 },
  ],
  mine: [
    { name: 'missed action', tier: 'Missed', chance: 0.15, min:1, max:1, value: 0},
    { name: 'stone', tier: 'Common', chance: 0.2, min: 1, max: 3, value: 5 },
    { name: 'copper', tier: 'Uncommon', chance: 0.2, min: 1, max: 3, value: 7 },
    { name: 'iron', tier: 'Uncommon', chance: 0.125, min: 1, max: 2, value: 10 },
    { name: 'silver', tier: 'Uncommon', chance: 0.125, min: 1, max: 2, value: 12 },
    { name: 'gold', tier: 'Rare', chance: 0.05, min: 1, max: 1, value: 20 },
    { name: 'platinum', tier: 'Rare', chance: 0.05, min: 1, max: 1, value: 22 },
    { name: 'diamond', tier: 'Epic', chance: 0.025, min: 1, max: 1, value: 100 },
    { name: 'ruby', tier: 'Epic', chance: 0.025, min: 1, max: 1, value: 110 },
    { name: 'emerald', tier: 'Legendary', chance: 0.02, min: 1, max: 1, value: 200 },
    { name: 'sapphire', tier: 'Legendary', chance: 0.02, min: 1, max: 1, value: 210 },
    { name: 'magic crystal', tier: 'Mythic', chance: 0.005, min: 1, max: 1, value: 400 },
    { name: 'arcane gem', tier: 'Mythic', chance: 0.005, min: 1, max: 1, value: 420 },
  ],
  chop: [
    { name: 'missed action', tier: 'Missed', chance: 0.15, min:1, max:1, value: 0},
    { name: 'oak', tier: 'Common', chance: 0.40, min: 1, max: 5, value: 5 },
    { name: 'birch', tier: 'Uncommon', chance: 0.25, min: 1, max: 5, value: 10 },
    { name: 'maple', tier: 'Rare', chance: 0.10, min: 1, max: 5, value: 15 },
    { name: 'mahogany', tier: 'Epic', chance: 0.05, min: 1, max: 5, value: 25 },
    { name: 'ancient oak', tier: 'Legendary', chance: 0.04, min: 1, max: 5, value: 50 },
    { name: 'enchanted tree', tier: 'Mythic', chance: 0.01, min: 1, max: 5, value: 100 },
  ],
};

// Create creatures array
export const creatures = [
  {
    name: 'forest floor',
    health: 0,
    chance: 0.5,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/forest.png',
    loot: [
      { name: 'missed action', tier: 'Missed', chance: 0.25, min: 1, max: 1, value: 0 },
      { name: 'stick', tier: 'Common', chance: 0.15, min: 1, max: 5, value: 0.25 },
      { name: 'stone', tier: 'Common', chance: 0.1, min: 1, max: 2, value: 5 },
      { name: 'mushroom', tier: 'Uncommon', chance: 0.1, min: 1, max: 2, value: 6 },
      { name: 'berry', tier: 'Uncommon', chance: 0.1, min: 1, max: 3, value: 10 },
      { name: 'herb', tier: 'Uncommon', chance: 0.1, min: 1, max: 2, value: 10 },
      { name: 'worm', tier: 'Common', chance: 0.2, min: 1, max: 2, value: 0.10},
    ],
    manaLoss: 1,
  },
  {
    name: 'Goblin',
    health: 10,
    chance: 0.015625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/goblin.png',
    loot: [
      { name: 'Rusty Sword', tier: 'Common', chance: 0.5, min: 1, max: 2 },
      { name: 'Goblin Tooth', tier: 'Uncommon', chance: 0.3, min: 1, max: 4 },
      { name: 'Goblin Armour', tier: 'Uncommon', chance: 0.2, min: 1, max: 1 },
    ],
    manaLoss: 10,
  },
  {
    name: 'Deer',
    health: 8,
    chance: 0.03125,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/deer.png',
    loot: [
      { name: 'Deer Antler', tier: 'Uncommon', chance: 0.2, min: 1, max: 2 },
      { name: 'Deer Hide', tier: 'Common', chance: 0.5, min: 1, max: 4 },
      { name: 'Deer Meat', tier: 'Common', chance: 0.3, min: 1, max: 3 },
    ],
    manaLoss: 5,
  },
  {
    name: 'Grouse',
    health: 5,
    chance: 0.0625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/grouse.png',
    loot: [
      { name: 'Grouse Feather', tier: 'Common', chance: 0.6, min: 1, max: 3 },
      { name: 'Grouse Meat', tier: 'Common', chance: 0.4, min: 1, max: 2 },
    ],
    manaLoss: 5,
  },
  {
    name: 'Fox',
    health: 7,
    chance: 0.0030625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/fox.png',
    loot: [
      { name: 'Fox Pelt', tier: 'Uncommon', chance: 0.5, min: 1, max: 2 },
      { name: 'Fox Tail', tier: 'Uncommon', chance: 0.4, min: 1, max: 1 },
      { name: 'Fox Meat', tier: 'Rare',chance: 0.2, min: 1, max: 2 },
    ],
    manaLoss: 7,
  },
  {
    name: 'Raccoon',
    health: 6,
    chance: 0.0078125,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/raccoon.png',
    loot: [
      { name: 'Raccoon Pelt', tier: 'Uncommon', chance: 0.5, min: 1, max: 2 },
      { name: 'Raccoon Tail', tier: 'Uncommon', chance: 0.4, min: 1, max: 1 },
      { name: 'Raccoon Meat', tier: 'Rare', chance: 0.2, min: 1, max: 2 },
    ],
    manaLoss: 6,
  },
  {
    name: 'Bear',
    health: 25,
    chance: 0.0009765625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/bear.png',
    loot: [
      { name: 'Bear Pelt', tier: 'Rare', chance: 0.5, min: 1, max: 1 },
      { name: 'Bear Claw', tier: 'Epic', chance: 0.3, min: 1, max: 2 },
      { name: 'Bear Meat', tier: 'Epic', chance: 0.2, min: 1, max: 4 },
    ],
    manaLoss: 25,
  },
  {
    name: 'Rabbit',
    health: 3,
    chance: 0.25,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/rabbit.png',
    loot: [
      { name: 'Rabbit Pelt', tier: 'Common', chance: 0.3, min: 1, max: 2 },
      { name: 'Rabbit Foot', tier: 'Common', chance: 0.2, min: 1, max: 1 },
      { name: 'Rabbit Meat', tier: 'Common', chance: 0.5, min: 1, max: 2 },
    ],
    manaLoss: 3,
  },
  {
    name: 'Squirrel',
    health: 2,
    chance: 0.125,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/squirrel.png',
    loot: [
      { name: 'Squirrel Pelt', tier: 'Common', chance: 0.3, min: 1, max: 1 },
      { name: 'Squirrel Tail', tier: 'Common', chance: 0.4, min: 1, max: 1 },
      { name: 'Squirrel Meat', tier: 'Common', chance: 0.3, min: 1, max: 1 },
    ],
    manaLoss: 2,
  },
  {
    name: 'Boar',
    health: 15,
    chance: 0.001953125,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/boar.png',
    loot: [
      { name: 'Boar Tusk', tier: 'Uncommon', chance: 0.4, min: 1, max: 2 },
      { name: 'Boar Hide', tier: 'Rare', chance: 0.3, min: 1, max: 1 },
      { name: 'Boar Meat', tier: 'Rare', chance: 0.3, min: 1, max: 3 },
    ],
    manaLoss: 15,
  },
  {
    name: 'Wolf',
    health: 20,
    chance: 0.00048828125,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/wolf.png',
    loot: [
      { name: 'Wolf Pelt', tier: 'Epic', chance: 0.5, min: 1, max: 1 },
      { name: 'Wolf Fang', tier: 'Legendary', chance: 0.3, min: 1, max: 2 },
      { name: 'Wolf Claw', tier: 'Legendary', chance: 0.2, min: 1, max: 3 },
    ],
    manaLoss: 20,
  },
  {
    name: 'Ancient Rune',
    health: 0,
    chance: 0.00018310546875,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/ancient-rune.png',
    loot: [
      { name: 'Glacial Shard', tier: 'Legendary', chance: 0.25, min: 1, max: 1 },
      { name: 'Shadowroot Heart', tier: 'Legendary', chance: 0.25, min: 1, max: 1 },
      { name: 'Sunfire Ember', tier: 'Legendary', chance: 0.25, min: 1, max: 1 },
      { name: 'Magma Core', tier: 'Legendary', chance: 0.25, min: 1, max: 1 },
    ],
    manaLoss: 0,
  },
  {
    name: 'Misfit Rune',
    health: 50,
    chance: 0.00006103515625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/misfit-rune.png',
    loot: [
      { name: 'Mystic Rune', tier: 'Mythic', chance: 0.25, min: 1, max: 1, value: 15000 },
      { name: 'Arcane Rune', tier: 'Mythic', chance: 0.25, min: 1, max: 1, value: 15000 },
      { name: 'Melody Rune', tier: 'Mythic', chance: 0.25, min: 1, max: 1, value: 15000 },
      { name: 'Astral Rune', tier: 'Mythic', chance: 0.25, min: 1, max: 1, value: 15000 },
    ],
    manaLoss: 50,
  },
  {
    name: 'Giant Spider',
    health: 150,
    chance: 0.000244140625,
    imageUrl: 'https://mystic-misfits-bot.onrender.com/img/giant-spider.png',
    loot: [
      { name: 'Giant Spider Silk', tier: 'Legendary', chance: 0.5, min: 1, max: 3 },
      { name: 'Giant Spider Leg', tier: 'Legendary', chance: 0.3, min: 1, max: 2 },
      { name: 'Giant Spider Venom', tier: 'Legendary', chance: 0.2, min: 1, max: 3 },
    ],
    manaLoss: 75,
  },
];

// Define items found in the user's shop
export const shopItems = [
  { name: 'Sword', type: 'weapon', cost: 100 },
  { name: 'Axe', type: 'weapon', cost: 150 },
  { name: 'Bow', type: 'weapon', cost: 200 },
];